Feat: 181851206 Add vault data to soft verify Patient Info with logging
Notarise-gov-sg/api-notarise-healthcerts pull request #547
Opened 2022-04-26 04:36 UTC by zawmyolatt

**What does this PR do?**

- Read vault data from dynamoDB and compare with Patient's DOB, Gender and Name
- Add comparison result in logs to check for failure rate
- Update readme to setup local dynamoDB with docker localstack.

2022-04-26 08:31 UTC, HJunyuan requested changes

2022-04-26 08:31 UTC, HJunyuan commented on src/functionHandlers/notarisePdt/v2/handler.ts
> +          trace(`Is name in vault : ${isNameInVault}`);
- `traceWithRef()`
- Shall we combine all the trace logs into one statement? Easier to debug when searching in Kibana.

2022-04-26 08:31 UTC, HJunyuan commented on src/functionHandlers/notarisePdt/v2/handler.ts
> +          traceWithRef(`Is name in vault : ${isNameInVault}`);
Shall we combine all the trace logs into one statement? Easier to debug in Kibana.

Maybe something like:
```javascript
traceWithRef({ isDobInVault, isGenderInVault, isNameInVault });
```

2022-04-27 02:23 UTC, zawmyolatt commented on serverless.yml
> +        - "arn:aws:ssm:${self:provider.region}:${self:custom.accountId}:parameter/serverless/api-resident/HASH_SALT"
ah.. it's defined in api-resident when setup and also use that ssm in other repo like `api-notarise`

2022-04-27 05:26 UTC, HJunyuan approved these changes

2022-04-27 05:54 UTC, merged